trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: 'DockerBuild'
  displayName: "End-to-end Docker image build and push"
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 300

  variables:
    dockerId: cbica
    imageName: captk_centos7

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
      fetchDepth: 1  # the depth of commits to ask Git to fetch; defaults to no limit
    
    - script: |
        docker build -t $(dockerId)/$(imageName) .
        docker login -u $(dockerId) -p $(pswd)
        docker push $(dockerId)/$(imageName)
      env:
        pswd: $(dockerPassword)