trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: 'DockerBuild'
  displayName: "End-to-end Docker image build and push"
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 360

  variables:
    dockerId: cbica
    imageName: captk_centos7

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
      fetchDepth: 1  # the depth of commits to ask Git to fetch; defaults to no limit

    - task: Docker@1 
      displayName: 'Build the Image'
      inputs:
        containerregistrytype: 'container Registry'
        dockerRegistryEndpoint: sarthakpatiDockerHub
        imageName: 'cbica/captk_centos7:devtoolset-6'
        command: build an image
        dockerFile: '**/Dockerfile'

    - task: Docker@1
      displayName: Login
      inputs:
        containerregistrytype: 'container Registry'
        dockerRegistryEndpoint: sarthakpatiDockerHub
        command: login

    - task: Docker@1
      displayName: 'Push the Image'
      inputs:
        command: push an image
        imageName: 'cbica/captk_centos7:devtoolset-6'  